export enum TRANSACTION_STATUS {
  INITIATED = 'INITIATED',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}
export enum PAYMENT_PROVIDER {
  ESEWA = 'ESEWA',
  KHALTI = 'KHALTI',
  CONNECT_IPS = 'CONNECT_IPS',
  CASH = 'CASH',
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  FREE = 'FREE',
  NONE = 'NONE',
}