export enum PRIVILEGE_NAME {
  MAIN_FEATURE_1 = 'MAIN_FEATURE_1',
  MAIN_FEATURE_2 = 'MAIN_FEATURE_2',
  MAIN_FEATURE_3 = 'MAIN_FEATURE_3',
}

export enum PRIVILEGE_SUBNAME {
  USER = 'USER',
  ROLE = 'ROLE',
  PRIVILEGE = 'PRIVILEGE',
  SUB_FEATURE_1_1 = 'SUB_FEATURE_1_1',
  SUB_FEATURE_1_2 = 'SUB_FEATURE_1_2',
  SUB_FEATURE_2_1 = 'SUB_FEATURE_2_1',
  SUB_FEATURE_2_2 = 'SUB_FEATURE_2_2',
  MAIN_FEATURE_3_1 = 'MAIN_FEATURE_3_1',
  MAIN_FEATURE_3_2 = 'MAIN_FEATURE_3_2',
}

export const PRIVILEGE_GROUP = {
  MAIN_FEATURE_1: {
    USER:PRIVILEGE_SUBNAME.USER,
    SUB_FEATURE_1_1: PRIVILEGE_SUBNAME.SUB_FEATURE_1_1,
    SUB_FEATURE_1_2: PRIVILEGE_SUBNAME.SUB_FEATURE_1_2,
  },
  MAIN_FEATURE_2: {
    ROLE:PRIVILEGE_SUBNAME.ROLE,
    SUB_FEATURE_2_1: PRIVILEGE_SUBNAME.SUB_FEATURE_2_1,
    SUB_FEATURE_2_2: PRIVILEGE_SUBNAME.SUB_FEATURE_2_2,
  },
  MAIN_FEATURE_3: {
    PRIVILEGE:PRIVILEGE_SUBNAME.PRIVILEGE,
    MAIN_FEATURE_3_1: PRIVILEGE_SUBNAME.MAIN_FEATURE_3_1,
    MAIN_FEATURE_3_2: PRIVILEGE_SUBNAME.MAIN_FEATURE_3_2
  },
} as const;
